---
header-includes: |
  \usepackage{titling}
  \usepackage{float}
  \setlength{\droptitle}{-6em} 
title: "Assignment 1"
author:  "Viktória Kónya"
date: "`r format(Sys.time(), '%d %B %Y')`"
geometry: margin=1.8cm
fontsize: 9pt
output: 
  pdf_document:
    extra_dependencies: ["flafter"]
---

```{r setup, include=FALSE}

# Chunk setup
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

```{r import_libraries, echo = F, include = F}

# Clear environment
rm(list=ls())

# Import libraries
library(tidyverse)
library(modelsummary)
library(kableExtra)
library(gridExtra) # multiple-plots
# library(estimatr)
library(fixest)
library(caret) 
library(GGally) # pairwise 

```

```{r import_dataset, echo = F, include = F}

# Import dataset
df_orig <- read_csv("https://osf.io/4ay9x/download") 

```


```{r custom_function, echo = F, include = F}

# Create custom functions for visualization

# A. Histograms
histograms <- function( x_var , x_lab, bin ){
  n = nrow(df)
  
  ggplot( df , aes(x = x_var)) +
    geom_histogram( binwidth = bin, fill="#238b45", color = 'gray50', na.rm = T) +
    stat_function(fun = function(x) dnorm(x, mean = mean(x_var, na.rm = T), sd = sd(x_var, na.rm = T)) * n * bin, color = "darkred", size = 1, na.rm = T) +
    labs(y = 'Count',x = x_lab ) +
    theme_bw() +
      theme(
        plot.title = element_text(size = 12L,
        face = "bold", hjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        legend.position = "none"
     )
}

# B. Scatterplot
scatter <- function( data, x_var , y_var, x_lab, y_lab, chart_title){
  
  ggplot( data , aes(x = {{ x_var }}, y = {{ y_var }})) +
    geom_point(color="#2ca25f",size=0.5,alpha=0.6, na.rm = T) +
    geom_smooth(method="loess" , formula = y ~ x , na.rm = T)+
    labs(x = x_lab, y = y_lab) +
    #ggtitle(chart_title) +
    theme_bw() +
    theme(
    plot.title = element_text(size = 12L,
    face = "bold", hjust = 0.5),
    axis.title.y = element_text(face = "bold"),
    axis.title.x = element_text(face = "bold"),
    legend.position = "none"
    )
}

# C. Bin scatters
bin_scatters_multi <- function( data,  x_var , y_var, x_lab, y_lab){

  data %>%   
  ggplot() +
  geom_jitter(aes(x = as.factor({{ x_var }}), y = {{ y_var }}), width = 0.25, color = "#2ca25f", alpha = 0.6, size = 0.5) +
  geom_crossbar(data = df %>% group_by({{ x_var }}) %>% dplyr::summarize( avg = mean({{ y_var }}, na.rm = T)), aes(x = as.factor({{ x_var }}), y = avg, ymin = avg, ymax = avg), size=0.5,col="black", width = 0.4) +
  #scale_x_discrete(labels = c(lab_x1, lab_x2, lab_x3, lab_x4, lab_x5, "NA")) +
  labs(x = x_lab, y = y_lab) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 12L,
    face = "bold", hjust = 0.5),
    axis.title.y = element_text(face = "bold"),
    axis.title.x = element_text(face = "bold"),
    legend.position = "none"
 )
}

```


\vspace{-18mm}
### Introduction
\vspace{-3mm}

In this report I examine the ...

```{r data_cleaning_sample, echo = F, include = F}

# Data cleaning & sample selection ( -> same sample as in DA2 Assignment 1)

# Filter for occupation - 1020: Financial managers - 1401 obs.
df <- df_orig %>% filter( occ2012 %in% c(0120) )

# Data preparation
df <- df %>% 
  
  # Filter : has hourly earning larger than one dollar, min. BA degree, active age
  filter( uhours>=20 & earnwke>uhours & grade92>=43 & age>=21 & age<=64)  %>%
  
  # Create gender dummy and character version for summary table
  mutate( female = as.numeric( sex==2 ) ) %>% 
  mutate( female_char = case_when(
            female == 1 ~ "Female",
            female == 0 ~ "Male" )) %>%
  
  # Create hourly wage
  mutate( w = earnwke/uhours ) %>%
    
  # Create log hourly wage
  mutate( lnw = log( w ) ) %>%
    
  # Create age polinomials
  mutate(agesq=age^2,
         agecu=age^3,
         agequ = age^4) %>%
    
  # Create education groups for summary table
  mutate(educ = factor(case_when(
          grade92 == 43 ~ "BA Degree",
          grade92 == 44 ~ "MA Degree", 
          grade92 == 45 ~ "Professional",
          grade92 == 46 ~ "PhD"),
          levels = c("BA Degree", 
                     "MA Degree", 
                     "Professional",
                     "PhD"))) %>% 
    
  # Create education dummies
  mutate(
          educ_BA = ifelse(educ == "BA Degree", 1, 0),
          educ_MA = ifelse(educ == "MA Degree", 1, 0),  
          educ_Profess = ifelse(educ == "Professional", 1, 0),  
          educ_PhD = ifelse(educ == "PhD", 1, 0))  %>%

  # Create class flag
  mutate(class_cat = case_when(
            class %in% c('Government - Federal' , 'Government - State', 'Government - Local') ~ 0,
            class %in% c('Private, For Profit' , 'Private, Nonprofit') ~ 1)) %>%
         
  # Union membership
  mutate(union_membership = case_when(
            unionmme %in% c('Yes') ~ 1,
            unionmme %in% c('No') ~ 0))  %>%

  # Own child
  mutate(has_child = case_when(
            ownchild == 0 ~ 0,
            ownchild > 0 ~ 1))  %>%
  
  # Keep only the useful fields
  select(hhid, earnwke, uhours, w, lnw, age, agesq, agecu, agequ, female, class_cat, educ, educ_BA, educ_MA, educ_Profess, educ_PhD, union_membership, has_child, state, race, marital, ethnic)

  
# Check other variables 
unique(df$state)
unique(df$marital)
unique(df$race)
unique(df$ethnic)

# Summary
summary(df)

```


```{r eda_summary_table, echo = F, include = F}

# EDA

# A. Summary statistics
# Note: Moved to Appendix A1

P95 <- function(x){quantile(x,0.95,na.rm=T)}
P05 <- function(x){quantile(x,0.05,na.rm=T)}
Range <- function(x){max(x, na.rm = TRUE) - min(x, na.rm = TRUE)}
Missing <- function(x){sum(is.na(x))}

eda_summary_table <- datasummary(  
              ( `Earnings` = earnwke ) +
              ( `Hours worked` = uhours ) +
              ( `Hourly wage` = w ) +
              ( `Log of Hourly wage` = lnw ) + 
              ( `Age` = age ) +  
              ( `Female` = female ) +
              ( `Job type` = class_cat ) +
              ( `BA Degree` = educ_BA ) + 
              ( `MA Degree` = educ_MA ) +                 
              ( `Professional` = educ_Profess ) +                 
              ( `PhD` = educ_PhD ) +
              ( `Union member` = union_membership ) +
              ( `Child`= has_child ) ~
    (N + Missing + Mean + SD + Min + Max + Range + P05 + Median  + P95),
    data = df,
    title = 'Descriptive statistics' ) %>% 
    kableExtra::kable_styling(latex_options = "hold_position", font_size = 9)

# Summary
summary(df)


```



```{r eda_1_var_analysis, echo = F, include = F}

# EDA 

# B. Distributions
# Moved to Appendix A2

# Earnings
hist_earnings <- histograms(df$earnwke, 'Earings', bin = 100 ) 

# Hours worked
hist_hours_worked <- histograms(df$uhours, 'Hours worked', bin = 1)

# Hourly wage
hist_hourly_wage <- histograms(df$w, 'Hourly wage', bin = 3)

# Ln hourly wage
hist_log_hourly_wage <- histograms(df$lnw, 'Log of Hourly wage', bin = 0.1)

# Age
hist_age <- histograms(df$age, 'Age', bin = 3)

```


```{r eda_pairwise_analysis, echo = F, include = F}

# EDA

# C. Scatter plots

# Age
scatter_w_age <- scatter(data = df, x_var = age, y_var = w, x_lab = "Age", y_lab = "Hourly wages") 
scatter_logw_age <- scatter(data = df, x_var = age, y_var = lnw, x_lab = "Age", y_lab = "Log of Hourly wages") 

# D. Bin scatters

# Gender
bin_scatter_felame_w <- bin_scatters_multi(data = df, x_var = female, y_var = w, x_lab = "Gender", y_lab = "Hourly wages") + scale_x_discrete(labels = c("Male", "Female")) 

bin_scatter_felame_logw <- bin_scatters_multi(data = df, x_var = female, y_var = lnw, x_lab = "Gender", y_lab = "Log of Hourly wages") + scale_x_discrete(labels = c("Male", "Female")) 


# Job type
bin_scatter_jobtype_w <- bin_scatters_multi(data = df, x_var = class_cat, y_var = w, x_lab = "Job type", y_lab = "Hourly wages") + scale_x_discrete(labels = c("Government", "Private")) 

bin_scatter_jobtype_logw <- bin_scatters_multi(data = df, x_var = class_cat, y_var = lnw, x_lab = "Job type", y_lab = "Log of Hourly wages") + scale_x_discrete(labels = c("Government", "Private")) 


# Education
bin_scatter_educ_w <- bin_scatters_multi(data = df, x_var = educ, y_var = w, x_lab = "Education level", y_lab = "Hourly wages") + scale_x_discrete(labels = c("BA Degree", "MA Degree", "Professional", "PhD")) 

bin_scatter_educ_logw <- bin_scatters_multi(data = df, x_var = educ, y_var = lnw, x_lab = "Education level", y_lab = "Log of Hourly wages") + scale_x_discrete(labels = c("BA Degree", "MA Degree", "Professional", "PhD")) 


# Union membership
bin_scatter_union_w <- bin_scatters_multi(data = df, x_var = union_membership, y_var = w, x_lab = "Member of union", y_lab = "Hourly wages") + scale_x_discrete(labels = c("No", "Yes")) 

bin_scatter_union_logw <- bin_scatters_multi(data = df, x_var = union_membership, y_var = lnw, x_lab = "Member of union", y_lab = "Log of Hourly wages") + scale_x_discrete(labels = c("No", "Yes")) 


# Child
bin_scatter_child_w <- bin_scatters_multi(data = df, x_var = has_child, y_var = w, x_lab = "Has own child", y_lab = "Hourly wages") + scale_x_discrete(labels = c("No", "Yes")) 

bin_scatter_child_logw <- bin_scatters_multi(data = df, x_var = has_child, y_var = lnw, x_lab = "Has own child", y_lab = "Log of Hourly wages") + scale_x_discrete(labels = c("No", "Yes")) 

# State
bin_scatters_multi(data = df, x_var = state, y_var = lnw, x_lab = "State", y_lab = "Log of Hourly wages") 


# Pairwise summary table
# ggpairs(df %>% select(-c(state, hhid, educ, uhours, earnwke, agesq, agecu, agequ)))


```



















\newpage
### Appendix
### A1. Descriptive statistics

```{r A1_eda_summary_table, echo = F}

# Descriptive statistics
eda_summary_table

```


\newpage
### A2. One variable analysis

```{r A2_eda_1_var_analysis, echo = F, fig.align='center', fig.height=8, fig.width=10}

# Histograms
grid.arrange( grobs = list(
              hist_earnings,
              hist_hours_worked,
              hist_hourly_wage, 
              hist_log_hourly_wage,
              hist_age),
             ncol=2,
             top = "Fig1.: Histograms",
             bottom = "Note: .")

```


\newpage
### A3. Relationship with outcome variable

```{r A3_eda_2_var_analysis1, echo = F, fig.align='center', fig.height=14, fig.width=10}

# Relationship with outcome
grid.arrange( grobs = list(
              scatter_w_age,
              scatter_logw_age,
              bin_scatter_felame_w, 
              bin_scatter_felame_logw,
              bin_scatter_jobtype_w, 
              bin_scatter_jobtype_logw,
              bin_scatter_educ_w, 
              bin_scatter_educ_logw),
             ncol=2,
             top = "Fig2.: Histograms",
             bottom = "Note: .")

```

\newpage
```{r A3_eda_2_var_analysis2, echo = F, fig.align='center', fig.height=7, fig.width=10}

# Relationship with outcome
grid.arrange( grobs = list(
              bin_scatter_union_w,
              bin_scatter_union_logw,
              bin_scatter_child_w, 
              bin_scatter_child_logw),
             ncol=2,
             top = "Fig2.: Histograms",
             bottom = "Note: .")

```


\newpage
### A4. Interactions

\newpage
### A5. Regression
